"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'media/ear.jpeg',
    'plist': {
        'CFBundleName': 'SystemTrayApp',
        'CFBundleIdentifier': 'com.example.SystemTrayApp',
        'LSUIElement': 1,
    },
    'packages': ['PyQt6'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
